# -*- coding: utf-8 -*-

# import_error implementation generated from reading ui file '.\error1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_import_error(object):
    def setupUi(self, import_error):
        import_error.setObjectName("import_error")
        import_error.resize(342, 244)
        import_error.setMinimumSize(QtCore.QSize(237, 102))
        self.widget = QtWidgets.QWidget(import_error)
        self.widget.setGeometry(QtCore.QRect(30, 70, 279, 95))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(277, 29))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(import_error)
        QtCore.QMetaObject.connectSlotsByName(import_error)

    def retranslateUi(self, import_error):
        _translate = QtCore.QCoreApplication.translate
        import_error.setWindowTitle(_translate("import_error", "import_error"))
        self.label.setText(_translate("import_error", "No \'Datasets\' folder found"))
        self.pushButton.setText(_translate("import_error", "Browse"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    error = QtWidgets.QMainWindow()
    ui = Ui_import_error()
    ui.setupUi(error)
    error.show()
    sys.exit(app.exec_())