# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'import_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(559, 376)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.db_root = QtWidgets.QLabel(self.centralwidget)
        self.db_root.setObjectName("db_root")
        self.horizontalLayout.addWidget(self.db_root)
        self.db_name = QtWidgets.QLineEdit(self.centralwidget)
        self.db_name.setObjectName("db_name")
        self.horizontalLayout.addWidget(self.db_name)
        self.browse1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse1.sizePolicy().hasHeightForWidth())
        self.browse1.setSizePolicy(sizePolicy)
        self.browse1.setObjectName("browse1")
        self.horizontalLayout.addWidget(self.browse1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ds_root = QtWidgets.QLabel(self.centralwidget)
        self.ds_root.setObjectName("ds_root")
        self.horizontalLayout_2.addWidget(self.ds_root)
        self.ds_name = QtWidgets.QLineEdit(self.centralwidget)
        self.ds_name.setObjectName("ds_name")
        self.horizontalLayout_2.addWidget(self.ds_name)
        self.browse2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse2.sizePolicy().hasHeightForWidth())
        self.browse2.setSizePolicy(sizePolicy)
        self.browse2.setObjectName("browse2")
        self.horizontalLayout_2.addWidget(self.browse2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.datasets = QtWidgets.QLabel(self.centralwidget)
        self.datasets.setObjectName("datasets")
        self.horizontalLayout_3.addWidget(self.datasets)
        self.load = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load.sizePolicy().hasHeightForWidth())
        self.load.setSizePolicy(sizePolicy)
        self.load.setObjectName("Load")
        self.horizontalLayout_3.addWidget(self.load)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.dataset_list = QtWidgets.QListWidget(self.centralwidget)
        self.dataset_list.setObjectName("dataset_list")
        self.verticalLayout.addWidget(self.dataset_list)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 559, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.db_root.setText(_translate("MainWindow", "Database root:"))
        self.browse1.setText(_translate("MainWindow", "Browse"))
        self.ds_root.setText(_translate("MainWindow", "Dataset folder:"))
        self.browse2.setText(_translate("MainWindow", "Browse"))
        self.datasets.setText(_translate("MainWindow", "Datasets:"))
        self.load.setText(_translate("MainWindow", "Load"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_LoadWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
