# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'import_error.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_import_error(object):
    def setupUi(self, import_error):
        import_error.setObjectName("import_error")
        import_error.resize(377, 363)
        self.centralwidget = QtWidgets.QWidget(import_error)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        import_error.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(import_error)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 377, 43))
        self.menubar.setObjectName("menubar")
        import_error.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(import_error)
        self.statusbar.setObjectName("statusbar")
        import_error.setStatusBar(self.statusbar)

        self.retranslateUi(import_error)
        QtCore.QMetaObject.connectSlotsByName(import_error)

    def retranslateUi(self, import_error):
        _translate = QtCore.QCoreApplication.translate
        import_error.setWindowTitle(_translate("import_error", "import_error"))
        self.label.setText(_translate("import_error", "No folder found "))
        self.pushButton.setText(_translate("import_error", "browse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    error = QtWidgets.QMainWindow()
    ui = Ui_import_error()
    ui.setupUi(error)
    error.show()
    sys.exit(app.exec_())